### ISSUE TITLE
Release 1

### ISSUE THREAD

**Issue by elliotthomasdev** [elliotthomasdev/zombieFight#2]
Release 1 code and pull request reviews.

**Comment by dragonpale1** [comment]
I'm just adding a comment to work this system a little.  I have pulled the latest changes from Git on a compiler and the program runs successfully there. I am ready to sign off on release version 1.

**Comment by Jadeturgeon** [comment]
Sorry I missed the meeting I had to work late I just looked at the release
version 1 looks great it’s running on mine as well! Are we all supposed to
upload our codes or add to yours? Sorry I am a little confused and want to
be on the same page again I apologize for missing the meeting!

**Comment by Jadeturgeon** [comment]
Program running great closing issue
