### ISSUE TITLE
Determine New Requirements Plan For Release 3

### ISSUE THREAD

**Issue by dragonpale1** [elliotthomasdev/zombieFight#23]
Looks like there are 5 areas to manage in order to completely code the updates for Release 3. I will volunteer to create a plan for this since I am as familiar with the codebase as anyone. If anyone else wants to participate, maybe indicate some interest via email? 

BREAKING DOWN REQUIREMENTS
1. Add weapons.  
2. The weapon cache is randomly generated.  
3. The survivors randomly picked a weapon.  
4. Each weapon has different damage level and accuracy.    For example, shot gun does more damage than a pistol but less accurate.  Sometimes the shotgun will miss the target.  You are free to choose the damage level and accuracy for each weapon.   
5. The sample run is similar to release 2 but it should indicate the weapon used to kill an infected.

    Some weapons from the game include:
    Shotgun
    Submachine gun
    Assaut Rifle
    Pistal
    Axe
    Crowbar
    Frying Pane

**Comment by dragonpale1** [comment]
I have a design ready for how we can implement this. I'll move this to the middle column. Anyone else who wants to take a shot, please leave a comment.

**Comment by elliotthomasdev** [comment]
Hi Sean, once you have an implemented weapon I could maybe take a look at your process and then attempt to implement a few myself? Your overall plan and approach to the code base has been excellent   so far and I personally would like to continue with your process.

**Comment by dragonpale1** [comment]
No additional plans/designs have come in so I am closing this issue and have sent a message requesting that team members approve or object to the plan on the table.
