### ISSUE TITLE
Team work reviews and file check ins availability

### ISSUE THREAD

**Issue by dragonpale1** [elliotthomasdev/zombieFight#24]
Please leave a comment with your availability if you are free on Tuesday night, Wednesday night, or both. Please also send a team email if availability on either of those nights is an issue and we need to discuss it.

**Comment by dragonpale1** [comment]
Sean: I am available both nights and will plan to work to coordinate on both or either.

**Comment by elliotthomasdev** [comment]
I am also available both nights!

**Comment by dragonpale1** [comment]
Elliot - that is terrific. Since that's a "quorum" I think we can plan to set up a chat tomorrow and get started on this. I'll send you an email shortly and we can hammer out a time. 

I'd like to wait and see if Jade chips in as well but I will include her on the email so she has the opportunity to join in.

**Comment by elliotthomasdev** [comment]
Sounds good!

**Comment by dragonpale1** [comment]
Discussion about how to split up final responsibilities has taken place and we will be updating the files shortly.
