### ISSUE TITLE
Work Request for Jade

### ISSUE THREAD

**Issue by dragonpale1** [elliotthomasdev/zombieFight#34]
Hi Jade,

One thing we did in updating this was to put all the derived Weapon classes in the same file with the base abstract Weapon class. It's inconsistent with the Zombies and Survivors derived classes, they are all in their own files. We should do the same here. Would you be OK moving each of those classes to its own separate file? 

Here are the steps that we have been following in working with this project. You can use this issue to track your work or leave comments and notes about the steps you've taken and we should all be kept up to date since we are all assigned to it.

1. Create a branch off the master just for your work.
2. Create the new files
3. When you are satisfied everything is ready for check-in/commit, create a pull request and let the team know, we are reviewing each other's pull requests.

When you are finished, we should be almost ready to build release 3.

**Comment by Jadeturgeon** [comment]
Separated files uploading and creating pull request now

**Comment by Jadeturgeon** [comment]
Hey guys I separate the files and uploaded were you able to see a pull
request? Not sure if it worked I created a branch called separated weapons.
Let me know

**Comment by dragonpale1** [comment]
The files didn't merge into the project folder, they merged on the top level. I will do some cleanup to get them into the project.

**Comment by dragonpale1** [comment]
OK. The files are moved and some Java filenaming freakouts were resolved. We should be good to go now.
